version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "06:00"
    labels:
      - "dependencies"
    open-pull-requests-limit: 20
    cooldown:
      default-days: 3
      semver-major-days: 7
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"
