{{- if eq .Values.mode "cronjob" }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "rootly-catalog-sync.fullname" . }}
  labels:
    {{- include "rootly-catalog-sync.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  startingDeadlineSeconds: {{ .Values.cronjob.startingDeadlineSeconds }}
  concurrencyPolicy: {{ .Values.cronjob.concurrencyPolicy }}
  jobTemplate:
    metadata:
      labels:
        {{- include "rootly-catalog-sync.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      backoffLimit: {{ .Values.cronjob.backoffLimit }}
      ttlSecondsAfterFinished: {{ .Values.cronjob.ttlSecondsAfterFinished }}
      template:
        metadata:
          labels:
            {{- include "rootly-catalog-sync.selectorLabels" . | nindent 12 }}
            {{- with .Values.podLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          restartPolicy: {{ .Values.cronjob.restartPolicy }}
          {{- include "rootly-catalog-sync.podSpec" . | nindent 10 }}
{{- end }}
