{{- if and .Values.rootly.apiKey (not .Values.rootly.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rootly-catalog-sync.fullname" . }}
  labels:
    {{- include "rootly-catalog-sync.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.rootly.secretKey }}: {{ .Values.rootly.apiKey | b64enc | quote }}
{{- end }}
