{{- if and .Values.agent.controlPlaneEnabled (not .Values.enrollment.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rootly-private-agent.fullname" . }}
  labels:
    {{- include "rootly-private-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.enrollment.secretKey }}: {{ .Values.enrollment.token | quote }}
{{- end }}
